apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: busybox
  labels:
    run: busybox
spec:
  replicas: 5
  selector:
    matchLabels:
      run: busybox
  template:
    metadata:
      labels:
        run: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        ports:
          - containerPort: 1234
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
